"""Date column added

Revision ID: 1a687013c830
Revises: b4961e966a7d
Create Date: 2022-05-27 02:39:10.753517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a687013c830'
down_revision = 'b4961e966a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'date')
    # ### end Alembic commands ###
