"""region column added

Revision ID: 2eaf603f9134
Revises: bdcb27a4afd1
Create Date: 2022-05-27 13:01:49.466319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eaf603f9134'
down_revision = 'bdcb27a4afd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('region', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'region')
    # ### end Alembic commands ###
